# Automatically generated by Pynguin.
from unittest import TestCase

import main as module0
import unittest


def test_case_0():
    var0 = module0.print_output()
    assert var0 is None


def test_case_1():
    var0 = '~29Dq\\G'
    var1 = module0.get_max_extention_length(var0)
    assert var1 is not None


def test_case_2():
    var0 = '~29Dq\\G'
    var1 = module0.get_max_extention_length(var0)
    assert var1 is not None
    var2 = module0.get_input()


def test_case_3():
    var0 = '~29Dq\\G'
    var1 = module0.get_max_extention_length(var0)
    assert var1 is not None
    var2 = module0.get_input()
    var3 = module0.print_output()
    var4 = '~29Dq\\G'
    var5 = module0.get_max_extention_length(var4)
    var6 = False
    var7 = module0.get_max_extention_length(var6)


def test_case_4():
    var0 = '~29Dq\\G'
    var1 = module0.get_max_extention_length(var0)
    assert var1 is not None
    var2 = '~29Dq\\G'
    var3 = module0.get_max_extention_length(var2)
    assert var3 is not None
    var4 = module0.get_input()
    var5 = module0.print_output()
    var6 = '~29Dq\\G'
    var7 = module0.get_max_extention_length(var6)
    var8 = False
    var9 = module0.get_max_extention_length(var8)
    var10 = module0.get_input()


def test_case_5():
    var0 = '~29Dq\\G'
    var1 = module0.get_max_extention_length(var0)
    assert var1 is not None
    var2 = module0.get_input()
    var3 = module0.print_output()
    var4 = '~29Dq\\G'
    var5 = module0.get_max_extention_length(var4)
    var6 = False
    var7 = module0.get_max_extention_length(var6)
    var8 = '~29Dq\\G'
    var9 = module0.get_max_extention_length(var8)
    var10 = module0.get_input()
    var11 = module0.print_output()
    var12 = b'\x0b/K\xc3\xdb\x1c\x1a\x18!'
    var13 = module0.read_operator_rate_file(var12)


def test_case_6():
    var0 = '~29Dq\\G'
    var1 = module0.get_max_extention_length(var0)
    assert var1 is not None
    var2 = module0.print_output()
    assert var2 is None
    var3 = '~29Dq\\G'
    var4 = module0.get_max_extention_length(var3)
    assert var4 is not None
    var5 = module0.get_input()
    var6 = '~29Dq\\G'
    var7 = module0.get_max_extention_length(var6)
    var8 = module0.get_input()
    var9 = module0.print_output()
    var10 = '~29Dq\\G'
    var11 = module0.get_max_extention_length(var10)
    var12 = False
    var13 = module0.get_max_extention_length(var12)
    var14 = None
    var15 = module0.get_max_extention_length(var14)


def test_case_7():
    var0 = '~29Dq\\G'
    var1 = module0.get_max_extention_length(var0)
    assert var1 is not None
    var2 = module0.get_input()
    var3 = module0.print_output()
    var4 = '~29Dq\\G'
    var5 = module0.get_max_extention_length(var4)
    var6 = False
    var7 = module0.get_max_extention_length(var6)
    var8 = module0.get_input()


def test_case_8():
    var0 = '~29Dq\\G'
    var1 = module0.get_max_extention_length(var0)
    assert var1 is not None
    var2 = module0.get_input()
    var3 = module0.print_output()
    var4 = '~29Dq\\G'
    var5 = module0.get_max_extention_length(var4)
    var6 = False
    var7 = module0.get_max_extention_length(var6)
    var8 = module0.get_input()
    var9 = '~29Dq\\G'
    var10 = module0.get_max_extention_length(var9)
    var11 = module0.get_input()
    var12 = module0.print_output()
    var13 = '~29Dq\\G'
    var14 = module0.get_max_extention_length(var13)
    var15 = False
    var16 = module0.get_max_extention_length(var15)
    var17 = '~29Dq\\G'
    var18 = module0.get_max_extention_length(var17)
    var19 = module0.print_output()
    var20 = '~29Dq\\G'
    var21 = module0.get_max_extention_length(var20)
    var22 = module0.get_input()
    var23 = '0j-<xI,\t~+8'
    var24 = module0.read_operator_rate_file(var23)


def test_case_9():
    var0 = '~29Dq\\G'
    var1 = module0.get_max_extention_length(var0)
    assert var1 is not None
    var2 = module0.get_input()
    var3 = '~29Dq\\G'
    var4 = module0.get_max_extention_length(var3)
    var5 = '~29Dq\\G'
    var6 = module0.get_max_extention_length(var5)
    var7 = module0.get_input()
    var8 = module0.print_output()
    var9 = '~29Dq\\G'
    var10 = module0.get_max_extention_length(var9)
    var11 = False
    var12 = module0.get_max_extention_length(var11)
    var13 = None
    var14 = module0.get_max_extention_length(var13)

    if __name__ == '__main__':
        unittest.main()
