# Automatically generated by Pynguin.
import main as module0


def test_case_0():
    try:
        var0 = -2195.3716
        var1 = module0.get_max_extention_length(var0)
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = None
        var1 = module0.read_operator_rate_file(var0)
    except BaseException:
        pass


def test_case_2():
    try:
        var0 = None
        var1 = module0.cheapest_call_rate(var0)
    except BaseException:
        pass


def test_case_3():
    try:
        var0 = '~29Dq\\G'
        var1 = module0.get_max_extention_length(var0)
        assert var1 is not None
        var2 = module0.print_output()
        assert var2 is None
        var3 = False
        var4 = module0.extract_operator_extention(var3)
    except BaseException:
        pass


def test_case_4():
    try:
        var0 = b'\xb5=\xe6)I\xf5\xa3Ghs'
        var1 = module0.get_max_extention_length(var0)
    except BaseException:
        pass


def test_case_5():
    try:
        var0 = module0.print_output()
        assert var0 is None
        var1 = '~29Dq\\G'
        var2 = module0.get_max_extention_length(var1)
        assert var2 is not None
        var3 = None
        var4 = module0.read_operator_rate_file(var3)
    except BaseException:
        pass


def test_case_6():
    try:
        var0 = module0.print_output()
        assert var0 is None
        var1 = '~29Dq\\G'
        var2 = module0.get_max_extention_length(var1)
        assert var2 is not None
        var3 = 1899.829
        var4 = module0.get_max_extention_length(var3)
    except BaseException:
        pass


def test_case_7():
    try:
        var0 = -1358.101906
        var1 = module0.cheapest_call_rate(var0)
    except BaseException:
        pass


def test_case_8():
    try:
        var0 = b'>\x11'
        var1 = module0.get_max_extention_length(var0)
    except BaseException:
        pass
